### ISSUE TITLE
TypeError: Cannot read property 'setPrice' of undefined, on running truffle test 

### ISSUE THREAD

**Issue by yaseenumar** [ChenchenYo/SimpleMonitor#2]
**Hi,
After installing all the node packages, i tried running "truffle test" command against Ganache network. It does some registration stuff and runs till step 1 and gets stuck on that step.For all 96 rounds it throws an error as shown below:**  
Contract: simpletest
       round 96 should be executed :
     TypeError: Cannot read property 'setPrice' of undefined
      at execute (D:/yasee/MS_utd/semester 4/independent study/SimpleMonitor-master/test/simpletest.js:373:7)
      at D:/yasee/MS_utd/semester 4/independent study/SimpleMonitor-master/test/simpletest.js:290:33
      at step (D:/yasee/MS_utd/semester 4/independent study/SimpleMonitor-master/test/simpletest.js:288:13)
      at _callee2$ (D:/yasee/MS_utd/semester 4/independent study/SimpleMonitor-master/test/simpletest.js:508:11)
      at tryCatch (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\simpletest.js:102:191)
      at test\simpletest.js:102:437
      at new Promise (<anonymous>)
      at test\simpletest.js:102:99
      at oneRound (test\simpletest.js:80:18)
      at Context._callee$ (D:/yasee/MS_utd/semester 4/independent study/SimpleMonitor-master/test/simpletest.js:139:20)
      at tryCatch (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:117:21)
      at step (test\simpletest.js:102:191)
      at test\simpletest.js:102:437
      at new Promise (<anonymous>)
      at Context.<anonymous> (test\simpletest.js:102:99)
      at C:\Users\yasee\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\testing\testrunner.js:135:1
      at C:\Users\yasee\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\property.js:119:1
      at C:\Users\yasee\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:89:1
      at C:\Users\yasee\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1

**Comment by QYuQianchen** [comment]
Hey, 
Thanks for the report. Which test file did you run? Also, have you increased the number of accounts in Ganache?

**Comment by yaseenumar** [comment]
I simply ran the command >> truffle test  and got the above error.
Which accounts should be added and how many?
Thanks,
Yaseen

**Comment by yaseenumar** [comment]
Hi,
Which truffle version did you use for this project Truffle 2.x or 3.x?

**Comment by yaseenumar** [comment]
> Hi,
> Which truffle version did you use for this project Truffle 2.x or 3.x?

and also the operating system
Thanks,
Yaseen

**Comment by yaseenumar** [comment]
I was able to run your test script "Simpletest" after creating new accounts each for SingleHouseFactory
SinglePVFactory, SingleBatteryFactory, SingleHeatPumpFactory, SingleWaterTankFactory, GridFactory and ,Configuration using command (e.g.)**web3.personal.newAccount("SingleHouseFactory")** in truffle console.

Thanks for the guidance! closing this issue now
